python train.py -train_from_extractor ../ext_model_nyt_layer1/model_step_7000.pt \
-train_from_abstractor ../models_abs_nyt/model_step_12000.pt \
--hybrid_loss -lr 0.002 -task hybrid \
-mode train -model_path=../models_hybrid_nyt_loss \
-bert_data_path /home/ybai/downloads/bert_data_nyt50_maxpos/nyt50 \
-ext_dropout 0.1 -visible_gpus 4,6 -report_every 50 \
-save_checkpoint_steps 2500 -batch_size 3000 \
-train_steps 200000 -accum_count 5  \
-log_file ../logs/hybrid_bert_nyt_hyloss \
-use_interval true -warmup_steps 50000 \
-warmup_steps_dec 10000 -max_pos 512 
